language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
# command to install dependencies
install:
   - BLAS=None LAPACK=None ATLAS=None pip install -r requirements.txt
   - python setup.py install
# command to run tests
script: python -m unittest test
