language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
# command to install dependencies
before_install:
   - sudo apt-get install gfortran liblapack-dev libblas-dev libatlas-dev
install:
   - pip install -r requirements.txt
   - python setup.py install
# command to run tests
script: python -m unittest test
